-- ============================================================================
-- CONSTANCCE 1.1.29 — VÍNCULO PROFISSIONAL (PERSONAL/NUTRICIONISTA) E PRESCRIÇÕES
-- Execute UMA VEZ no Supabase SQL Editor, depois de SUPABASE_SECURITY_HARDENING_1_1_16.sql
-- (usa public.constancce_email_verified, public.consume_constancce_rate_limit e
-- public.constancce_profiles, já criados por aquele script).
--
-- Modelo: convite por e-mail com aceite (igual a constancce_friendships), mais uma
-- caixa de entrada de "prescrições" (constancce_prescriptions). O profissional grava
-- um payload opaco (treino ou refeição, no mesmo formato que o app já usa); a
-- aplicação de fato nos dados do aluno/paciente acontece no dispositivo dele, do
-- mesmo jeito que "treino compartilhado por link" já funciona hoje — este script
-- nunca escreve nos dados (workoutTemplates/dietSavedMeals) de outro usuário.
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- 1. VÍNCULO PROFISSIONAL
-- --------------------------------------------------------------------------
create table if not exists public.constancce_professional_links (
  id bigint generated by default as identity primary key,
  professional_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references auth.users(id) on delete cascade,
  link_type text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint constancce_professional_link_not_self check (professional_id <> client_id),
  constraint constancce_professional_link_type_check check (link_type in ('personal','nutricionista')),
  constraint constancce_professional_link_status_check check (status in ('pending','accepted')),
  constraint constancce_professional_link_unique unique (professional_id, client_id, link_type)
);

alter table public.constancce_professional_links enable row level security;
revoke all on table public.constancce_professional_links from anon, authenticated;

create index if not exists constancce_professional_links_professional_idx
  on public.constancce_professional_links(professional_id);
create index if not exists constancce_professional_links_client_idx
  on public.constancce_professional_links(client_id);

-- --------------------------------------------------------------------------
-- 2. PRESCRIÇÕES (caixa de entrada — aplicada localmente pelo cliente)
-- --------------------------------------------------------------------------
create table if not exists public.constancce_prescriptions (
  id bigint generated by default as identity primary key,
  link_id bigint not null references public.constancce_professional_links(id) on delete cascade,
  professional_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  payload jsonb not null,
  note text,
  status text not null default 'sent',
  created_at timestamptz not null default now(),
  applied_at timestamptz,
  constraint constancce_prescription_kind_check check (kind in ('workout','diet')),
  constraint constancce_prescription_status_check check (status in ('sent','applied','dismissed'))
);

alter table public.constancce_prescriptions enable row level security;
revoke all on table public.constancce_prescriptions from anon, authenticated;

create index if not exists constancce_prescriptions_client_status_idx
  on public.constancce_prescriptions(client_id, status);
create index if not exists constancce_prescriptions_link_idx
  on public.constancce_prescriptions(link_id);

-- --------------------------------------------------------------------------
-- 3. CONVITE (só PRO pode convidar; grátis para aceitar/receber)
-- --------------------------------------------------------------------------
create or replace function public.invite_constancce_client(p_email text, p_link_type text)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_me uuid:=auth.uid(); v_client uuid; v_existing bigint; v_allowed boolean; v_is_pro boolean;
begin
  if v_me is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  if p_link_type not in ('personal','nutricionista') then raise exception 'invalid link type'; end if;
  if length(trim(coalesce(p_email,'')))<5 or length(trim(p_email))>254 or position('@' in p_email)<2 then raise exception 'invalid email'; end if;

  select coalesce(
    a.plan = 'lifetime'
    or (
      a.plan = 'trial'
      and a.payment_status = 'complimentary_trial'
      and a.trial_ends_at is not null
      and a.trial_ends_at > now()
    ), false
  )
  into v_is_pro
  from public.constancce_access a
  where a.user_id = v_me;
  if not coalesce(v_is_pro, false) then raise exception 'pro_required'; end if;

  select public.consume_constancce_rate_limit('proflink:'||v_me::text,20,86400) into v_allowed;
  if not coalesce(v_allowed,false) then raise exception 'too many requests'; end if;

  select p.user_id into v_client
  from public.constancce_profiles p join auth.users u on u.id=p.user_id and u.email_confirmed_at is not null
  where lower(p.email)=lower(trim(p_email)) limit 1;
  if v_client is null then raise exception 'user not found'; end if;
  if v_client=v_me then raise exception 'cannot add yourself'; end if;

  select id into v_existing from public.constancce_professional_links
  where professional_id=v_me and client_id=v_client and link_type=p_link_type limit 1;
  if v_existing is not null then raise exception 'link already exists'; end if;

  insert into public.constancce_professional_links(professional_id,client_id,link_type,status)
  values(v_me,v_client,p_link_type,'pending');
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.get_constancce_professional_links()
returns table(
  link_id bigint,
  direction text,
  link_type text,
  status text,
  user_id uuid,
  email text,
  display_name text,
  avatar_data_url text
)
language sql security definer set search_path=public,auth stable as $$
  select l.id,
    case when l.professional_id=auth.uid() then 'as_professional' else 'as_client' end,
    l.link_type, l.status, p.user_id, p.email, p.display_name, p.avatar_data_url
  from public.constancce_professional_links l
  join public.constancce_profiles p
    on p.user_id = case when l.professional_id=auth.uid() then l.client_id else l.professional_id end
  where public.constancce_email_verified() and (l.professional_id=auth.uid() or l.client_id=auth.uid())
  order by case when l.status='pending' then 0 else 1 end, l.created_at desc;
$$;

create or replace function public.respond_constancce_professional_link(p_link_id bigint, p_accept boolean)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  if p_accept then
    update public.constancce_professional_links set status='accepted',updated_at=now()
    where id=p_link_id and client_id=auth.uid() and status='pending';
  else
    delete from public.constancce_professional_links where id=p_link_id and client_id=auth.uid() and status='pending';
  end if;
  if not found then raise exception 'link request not found'; end if;
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.remove_constancce_professional_link(p_link_id bigint)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  delete from public.constancce_professional_links
  where id=p_link_id and (professional_id=auth.uid() or client_id=auth.uid());
  if not found then raise exception 'link not found'; end if;
  return jsonb_build_object('ok',true);
end;
$$;

-- --------------------------------------------------------------------------
-- 4. PRESCRIÇÕES: enviar (só PRO, só em vínculo aceito e do tipo compatível)
--    e receber/aplicar (o cliente decide localmente, isto só registra o status)
-- --------------------------------------------------------------------------
create or replace function public.send_constancce_prescription(p_link_id bigint, p_kind text, p_payload jsonb, p_note text default null)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_me uuid:=auth.uid(); v_link public.constancce_professional_links%rowtype; v_allowed boolean; v_is_pro boolean; v_note text;
begin
  if v_me is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  if p_kind not in ('workout','diet') then raise exception 'invalid kind'; end if;
  if p_payload is null or pg_column_size(p_payload) > 51200 then raise exception 'invalid payload'; end if;

  select * into v_link from public.constancce_professional_links
  where id=p_link_id and professional_id=v_me and status='accepted';
  if not found then raise exception 'link not found'; end if;

  if (v_link.link_type='personal' and p_kind<>'workout')
     or (v_link.link_type='nutricionista' and p_kind<>'diet') then
    raise exception 'kind mismatch for link type';
  end if;

  select coalesce(
    a.plan = 'lifetime'
    or (
      a.plan = 'trial'
      and a.payment_status = 'complimentary_trial'
      and a.trial_ends_at is not null
      and a.trial_ends_at > now()
    ), false
  )
  into v_is_pro
  from public.constancce_access a
  where a.user_id = v_me;
  if not coalesce(v_is_pro, false) then raise exception 'pro_required'; end if;

  select public.consume_constancce_rate_limit('prescription:'||v_me::text,30,86400) into v_allowed;
  if not coalesce(v_allowed,false) then raise exception 'too many requests'; end if;

  v_note := nullif(trim(coalesce(p_note,'')),'');
  if v_note is not null and length(v_note) > 500 then v_note := left(v_note,500); end if;

  insert into public.constancce_prescriptions(link_id,professional_id,client_id,kind,payload,note,status)
  values(p_link_id,v_me,v_link.client_id,p_kind,p_payload,v_note,'sent');

  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.get_constancce_prescriptions()
returns table(
  prescription_id bigint,
  link_id bigint,
  kind text,
  payload jsonb,
  note text,
  status text,
  created_at timestamptz,
  professional_user_id uuid,
  professional_email text,
  professional_name text
)
language sql security definer set search_path=public,auth stable as $$
  select pr.id, pr.link_id, pr.kind, pr.payload, pr.note, pr.status, pr.created_at,
    p.user_id, p.email, p.display_name
  from public.constancce_prescriptions pr
  join public.constancce_profiles p on p.user_id = pr.professional_id
  where public.constancce_email_verified() and pr.client_id=auth.uid()
  order by case when pr.status='sent' then 0 else 1 end, pr.created_at desc
  limit 200;
$$;

create or replace function public.respond_constancce_prescription(p_prescription_id bigint, p_action text)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  if p_action not in ('applied','dismissed') then raise exception 'invalid action'; end if;
  update public.constancce_prescriptions
  set status=p_action, applied_at=case when p_action='applied' then now() else applied_at end
  where id=p_prescription_id and client_id=auth.uid() and status='sent';
  if not found then raise exception 'prescription not found'; end if;
  return jsonb_build_object('ok',true);
end;
$$;

-- --------------------------------------------------------------------------
-- 5. GRANTS (somente RPC; nenhum acesso direto às tabelas)
-- --------------------------------------------------------------------------
revoke all on function public.invite_constancce_client(text,text) from public,anon;
revoke all on function public.get_constancce_professional_links() from public,anon;
revoke all on function public.respond_constancce_professional_link(bigint,boolean) from public,anon;
revoke all on function public.remove_constancce_professional_link(bigint) from public,anon;
revoke all on function public.send_constancce_prescription(bigint,text,jsonb,text) from public,anon;
revoke all on function public.get_constancce_prescriptions() from public,anon;
revoke all on function public.respond_constancce_prescription(bigint,text) from public,anon;

grant execute on function public.invite_constancce_client(text,text) to authenticated;
grant execute on function public.get_constancce_professional_links() to authenticated;
grant execute on function public.respond_constancce_professional_link(bigint,boolean) to authenticated;
grant execute on function public.remove_constancce_professional_link(bigint) to authenticated;
grant execute on function public.send_constancce_prescription(bigint,text,jsonb,text) to authenticated;
grant execute on function public.get_constancce_prescriptions() to authenticated;
grant execute on function public.respond_constancce_prescription(bigint,text) to authenticated;

commit;

-- Verificações opcionais após o RUN: ver SUPABASE_PROFESSIONAL_LINKS_VERIFY_1_1_29.sql
