-- =========================================================
-- CONSTANCCE — NOTIFICAÇÕES WEB PUSH
-- Execute no SQL Editor do Supabase.
-- É seguro executar mesmo se as tabelas já existirem.
-- =========================================================

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  timezone text not null default 'UTC',
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx
on public.push_subscriptions(user_id);

create table if not exists public.push_notification_log (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_key text not null,
  sent_at timestamptz not null default now(),
  unique (subscription_id, notification_key)
);

create index if not exists push_notification_log_sent_idx
on public.push_notification_log(sent_at);

create index if not exists push_notification_log_user_idx
on public.push_notification_log(user_id);

alter table public.push_subscriptions enable row level security;
alter table public.push_notification_log enable row level security;

-- As inscrições dos dispositivos são privadas.
-- O navegador grava/remove apenas através de Edge Functions autenticadas.
revoke all on table public.push_subscriptions from anon, authenticated;
revoke all on table public.push_notification_log from anon, authenticated;
