-- CONSTANCCE — PRODUCTION HARDENING
-- Execute uma vez no Supabase SQL Editor antes de ativar o novo sync por domínio.

begin;

create table if not exists public.constancce_domain_sync (
  user_id uuid not null references auth.users(id) on delete cascade,
  domain text not null check (domain in ('account','habits','tasks','goals','workouts','diet','finance')),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, domain)
);

alter table public.constancce_domain_sync enable row level security;

drop policy if exists "domain_sync_select_own" on public.constancce_domain_sync;
create policy "domain_sync_select_own"
on public.constancce_domain_sync
for select
to authenticated
using (user_id = auth.uid());

-- Escrita direta bloqueada: somente a Edge Function domain-sync (service role)
-- pode criar/alterar domínios. Isso impede contornar limites Free pelo REST.
drop policy if exists "domain_sync_insert_own" on public.constancce_domain_sync;
drop policy if exists "domain_sync_update_own" on public.constancce_domain_sync;
drop policy if exists "domain_sync_delete_own" on public.constancce_domain_sync;

create index if not exists constancce_domain_sync_updated_idx
  on public.constancce_domain_sync (user_id, updated_at desc);

-- O snapshot legado permanece legível apenas para migração/fallback de leitura.
-- A versão Production Ready escreve exclusivamente via domain-sync.
do $$
declare policy_row record;
begin
  for policy_row in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'device_sync'
      and cmd in ('INSERT', 'UPDATE', 'DELETE', 'ALL')
  loop
    execute format('drop policy if exists %I on public.device_sync', policy_row.policyname);
  end loop;
end $$;

drop policy if exists "device_sync_select_own_production" on public.device_sync;
create policy "device_sync_select_own_production"
on public.device_sync
for select
to authenticated
using (user_id = auth.uid());


create table if not exists public.constancce_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'analytics' check (kind in ('analytics','error')),
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  client_created_at timestamptz,
  app_version text,
  created_at timestamptz not null default now()
);

alter table public.constancce_events enable row level security;
-- Sem policy de escrita direta: apenas Service Role/Edge Function grava telemetria.

create index if not exists constancce_events_user_created_idx
  on public.constancce_events (user_id, created_at desc);

create index if not exists constancce_events_name_created_idx
  on public.constancce_events (event_name, created_at desc);


create table if not exists public.constancce_activity_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  event_type text not null,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

alter table public.constancce_activity_events enable row level security;

drop policy if exists "activity_events_select_own" on public.constancce_activity_events;
create policy "activity_events_select_own"
on public.constancce_activity_events
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "activity_events_insert_own" on public.constancce_activity_events;
-- Sem INSERT/UPDATE/DELETE direto para authenticated. A Edge Function
-- activity-event grava com Service Role e mantém o ledger append-only.
create index if not exists constancce_activity_events_user_time_idx
  on public.constancce_activity_events (user_id, occurred_at desc);

commit;
