-- ============================================================================
-- CONSTANCCE 1.1.16 — SECURITY HARDENING
-- Execute UMA VEZ no Supabase SQL Editor.
-- Mantém dados existentes e endurece permissões/RLS/checkout.
-- ============================================================================

begin;

-- --------------------------------------------------------------------------
-- 0. IDENTIDADE: somente e-mails realmente confirmados
-- --------------------------------------------------------------------------
create or replace function public.constancce_email_verified()
returns boolean
language sql
stable
security definer
set search_path = auth, public
as $$
  select exists(
    select 1 from auth.users
    where id = auth.uid() and email_confirmed_at is not null
  );
$$;
revoke all on function public.constancce_email_verified() from public, anon;
grant execute on function public.constancce_email_verified() to authenticated;

-- --------------------------------------------------------------------------
-- 1. DADOS PRIVADOS / SYNC
-- --------------------------------------------------------------------------
create table if not exists public.device_sync (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint device_sync_user_id_unique unique (user_id)
);

create table if not exists public.constancce_domain_sync (
  user_id uuid not null references auth.users(id) on delete cascade,
  domain text not null check (domain in ('account','habits','tasks','goals','workouts','diet','finance')),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, domain)
);

alter table public.device_sync enable row level security;
alter table public.constancce_domain_sync enable row level security;

-- Remove policies antigas do snapshot legado para evitar escrita REST.
do $$
declare p record;
begin
  for p in select policyname from pg_policies where schemaname='public' and tablename='device_sync'
  loop execute format('drop policy if exists %I on public.device_sync', p.policyname); end loop;
  for p in select policyname from pg_policies where schemaname='public' and tablename='constancce_domain_sync'
  loop execute format('drop policy if exists %I on public.constancce_domain_sync', p.policyname); end loop;
end $$;

create policy "device_sync_select_own_production"
on public.device_sync for select to authenticated using (user_id = auth.uid() and public.constancce_email_verified());

create policy "domain_sync_select_own"
on public.constancce_domain_sync for select to authenticated using (user_id = auth.uid() and public.constancce_email_verified());

revoke all on table public.device_sync from anon, authenticated;
revoke all on table public.constancce_domain_sync from anon, authenticated;
grant select on table public.device_sync to authenticated;
grant select on table public.constancce_domain_sync to authenticated;

create index if not exists device_sync_user_id_idx on public.device_sync(user_id);
create index if not exists constancce_domain_sync_updated_idx on public.constancce_domain_sync(user_id, updated_at desc);

-- --------------------------------------------------------------------------
-- 2. PLANOS / ACESSO
-- --------------------------------------------------------------------------
create table if not exists public.constancce_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'free',
  trial_started_at timestamptz,
  trial_ends_at timestamptz,
  payment_status text not null default 'none',
  preference_id text,
  payment_id text unique,
  payment_amount numeric(10,2),
  purchased_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.constancce_access alter column plan set default 'free';
alter table public.constancce_access alter column trial_started_at drop not null;
alter table public.constancce_access alter column trial_started_at drop default;
alter table public.constancce_access alter column trial_ends_at drop not null;
alter table public.constancce_access alter column trial_ends_at drop default;
alter table public.constancce_access drop constraint if exists constancce_access_plan_check;
alter table public.constancce_access add constraint constancce_access_plan_check check (plan in ('free','trial','lifetime'));
alter table public.constancce_access enable row level security;

drop policy if exists "constancce_access_select_own" on public.constancce_access;
create policy "constancce_access_select_own"
on public.constancce_access for select to authenticated using (user_id = auth.uid() and public.constancce_email_verified());

revoke all on table public.constancce_access from anon, authenticated;
grant select on table public.constancce_access to authenticated;

-- Novas contas SEMPRE começam Free. Não há e-mails especiais hardcoded.
create or replace function public.create_constancce_access_for_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.constancce_access(user_id, plan, trial_started_at, trial_ends_at, payment_status, updated_at)
  values(new.id, 'free', null, null, 'none', now())
  on conflict(user_id) do nothing;
  return new;
end;
$$;
revoke all on function public.create_constancce_access_for_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created_constancce_access on auth.users;
create trigger on_auth_user_created_constancce_access
after insert on auth.users for each row execute function public.create_constancce_access_for_new_user();

insert into public.constancce_access(user_id, plan, payment_status)
select u.id, 'free', 'none'
from auth.users u
left join public.constancce_access ca on ca.user_id=u.id
where ca.user_id is null
on conflict(user_id) do nothing;

-- Remove apenas trials automáticos antigos; trials administrativos são preservados.
update public.constancce_access
set plan='free', trial_started_at=null, trial_ends_at=null, updated_at=now()
where plan='trial' and coalesce(payment_status,'none') <> 'complimentary_trial';

-- PRO temporário só pode ser concedido administrativamente E para e-mail confirmado.
create or replace function public.grant_constancce_pro(user_email text, access_days integer default 30)
returns text language plpgsql security definer set search_path = public, auth as $$
declare
  v_id uuid;
  v_confirmed timestamptz;
  v_plan text;
begin
  if access_days < 1 or access_days > 365 then return 'Quantidade de dias inválida'; end if;
  select id,email_confirmed_at into v_id,v_confirmed
  from auth.users where lower(email)=lower(trim(user_email)) limit 1;
  if v_id is null then return 'Usuário não encontrado'; end if;
  if v_confirmed is null then return 'E-mail ainda não confirmado'; end if;
  select plan into v_plan from public.constancce_access where user_id=v_id;
  if v_plan='lifetime' then return 'Usuário já possui PRO vitalício'; end if;
  insert into public.constancce_access(user_id,plan,trial_started_at,trial_ends_at,payment_status,updated_at)
  values(v_id,'trial',now(),now()+make_interval(days=>access_days),'complimentary_trial',now())
  on conflict(user_id) do update set
    plan='trial', trial_started_at=now(), trial_ends_at=now()+make_interval(days=>access_days),
    payment_status='complimentary_trial', updated_at=now();
  return 'PRO temporário liberado com sucesso';
end;
$$;
revoke all on function public.grant_constancce_pro(text,integer) from public, anon, authenticated;
grant execute on function public.grant_constancce_pro(text,integer) to service_role;

create index if not exists constancce_access_plan_idx on public.constancce_access(plan);
create index if not exists constancce_access_trial_ends_idx on public.constancce_access(trial_ends_at);

-- --------------------------------------------------------------------------
-- 3. TELEMETRIA / ATIVIDADE
-- --------------------------------------------------------------------------
create table if not exists public.constancce_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'analytics' check (kind in ('analytics','error')),
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  client_created_at timestamptz,
  app_version text,
  created_at timestamptz not null default now()
);

create table if not exists public.constancce_activity_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  event_type text not null,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id,event_key)
);

alter table public.constancce_events enable row level security;
alter table public.constancce_activity_events enable row level security;
drop policy if exists "activity_events_select_own" on public.constancce_activity_events;
create policy "activity_events_select_own"
on public.constancce_activity_events for select to authenticated using (user_id=auth.uid() and public.constancce_email_verified());

revoke all on table public.constancce_events from anon, authenticated;
revoke all on table public.constancce_activity_events from anon, authenticated;
grant select on table public.constancce_activity_events to authenticated;

create index if not exists constancce_events_user_created_idx on public.constancce_events(user_id,created_at desc);
create index if not exists constancce_activity_events_user_time_idx on public.constancce_activity_events(user_id,occurred_at desc);

-- --------------------------------------------------------------------------
-- 4. PUSH
-- --------------------------------------------------------------------------
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  timezone text not null default 'UTC',
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_notification_log (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_key text not null,
  sent_at timestamptz not null default now(),
  unique(subscription_id,notification_key)
);

alter table public.push_subscriptions enable row level security;
alter table public.push_notification_log enable row level security;
revoke all on table public.push_subscriptions from anon, authenticated;
revoke all on table public.push_notification_log from anon, authenticated;
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);
create index if not exists push_notification_log_user_idx on public.push_notification_log(user_id);

-- --------------------------------------------------------------------------
-- 5. RATE LIMIT SERVER-SIDE
-- --------------------------------------------------------------------------
create table if not exists public.constancce_rate_limits (
  rate_key text primary key,
  window_started_at timestamptz not null default now(),
  hits integer not null default 0,
  updated_at timestamptz not null default now()
);
alter table public.constancce_rate_limits enable row level security;
revoke all on table public.constancce_rate_limits from anon, authenticated;

create or replace function public.consume_constancce_rate_limit(p_key text,p_limit integer,p_window_seconds integer)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_hits integer; v_window interval;
begin
  if length(coalesce(p_key,''))<12 or p_limit<1 or p_limit>5000 or p_window_seconds<1 or p_window_seconds>86400 then return false; end if;
  v_window:=make_interval(secs=>p_window_seconds);
  insert into public.constancce_rate_limits(rate_key,window_started_at,hits,updated_at)
  values(p_key,now(),1,now())
  on conflict(rate_key) do update set
    window_started_at=case when public.constancce_rate_limits.window_started_at < now()-v_window then now() else public.constancce_rate_limits.window_started_at end,
    hits=case when public.constancce_rate_limits.window_started_at < now()-v_window then 1 else public.constancce_rate_limits.hits+1 end,
    updated_at=now()
  returning hits into v_hits;
  return v_hits<=p_limit;
end;
$$;
revoke all on function public.consume_constancce_rate_limit(text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_constancce_rate_limit(text,integer,integer) to service_role;
create index if not exists constancce_rate_limits_updated_idx on public.constancce_rate_limits(updated_at);

-- --------------------------------------------------------------------------
-- 6. AMIGOS / PERFIS
-- --------------------------------------------------------------------------
create table if not exists public.constancce_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text not null default 'Usuário',
  avatar_data_url text,
  level integer not null default 1,
  rank_name text not null default 'Recruta',
  xp integer not null default 0,
  score integer not null default 0,
  streak_current integer not null default 0,
  streak_best integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.constancce_friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint constancce_friendship_not_self check(requester_id<>addressee_id),
  constraint constancce_friendship_direction_unique unique(requester_id,addressee_id)
);

alter table public.constancce_profiles enable row level security;
alter table public.constancce_friendships enable row level security;

drop policy if exists "constancce_profile_self_select" on public.constancce_profiles;
drop policy if exists "constancce_profile_self_insert" on public.constancce_profiles;
drop policy if exists "constancce_profile_self_update" on public.constancce_profiles;
create policy "constancce_profile_self_select" on public.constancce_profiles for select to authenticated using(user_id=auth.uid() and public.constancce_email_verified());
create policy "constancce_profile_self_insert" on public.constancce_profiles for insert to authenticated
with check(user_id=auth.uid() and public.constancce_email_verified() and lower(email)=lower(coalesce(auth.jwt()->>'email','')));
create policy "constancce_profile_self_update" on public.constancce_profiles for update to authenticated
using(user_id=auth.uid() and public.constancce_email_verified()) with check(user_id=auth.uid() and public.constancce_email_verified() and lower(email)=lower(coalesce(auth.jwt()->>'email','')));

-- Sem escrita direta em amizades. Toda mudança passa pelos RPCs abaixo.
revoke all on table public.constancce_profiles from anon, authenticated;
grant select,insert,update on table public.constancce_profiles to authenticated;
revoke all on table public.constancce_friendships from anon, authenticated;

create or replace function public.add_constancce_friend(p_email text)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
declare v_me uuid:=auth.uid(); v_friend uuid; v_existing bigint; v_allowed boolean;
begin
  if v_me is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  if length(trim(coalesce(p_email,'')))<5 or length(trim(p_email))>254 or position('@' in p_email)<2 then raise exception 'invalid email'; end if;
  select public.consume_constancce_rate_limit('friend:'||v_me::text,20,86400) into v_allowed;
  if not coalesce(v_allowed,false) then raise exception 'too many requests'; end if;
  select p.user_id into v_friend
  from public.constancce_profiles p join auth.users u on u.id=p.user_id and u.email_confirmed_at is not null
  where lower(p.email)=lower(trim(p_email)) limit 1;
  if v_friend is null then raise exception 'user not found'; end if;
  if v_friend=v_me then raise exception 'cannot add yourself'; end if;
  select id into v_existing from public.constancce_friendships
  where (requester_id=v_me and addressee_id=v_friend) or (requester_id=v_friend and addressee_id=v_me) limit 1;
  if v_existing is not null then raise exception 'friendship already exists'; end if;
  insert into public.constancce_friendships(requester_id,addressee_id,status) values(v_me,v_friend,'pending');
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.get_constancce_friends()
returns table(friendship_id bigint,user_id uuid,email text,display_name text,avatar_data_url text,level integer,rank_name text,xp integer,score integer,streak_current integer,streak_best integer,status text,direction text)
language sql security definer set search_path=public,auth stable as $$
  select f.id,p.user_id,p.email,p.display_name,p.avatar_data_url,p.level,p.rank_name,p.xp,p.score,p.streak_current,p.streak_best,f.status,
  case when f.requester_id=auth.uid() then 'sent' else 'received' end
  from public.constancce_friendships f
  join public.constancce_profiles p on p.user_id=case when f.requester_id=auth.uid() then f.addressee_id else f.requester_id end
  where public.constancce_email_verified() and (f.requester_id=auth.uid() or f.addressee_id=auth.uid())
  order by case when f.status='pending' then 0 else 1 end,p.xp desc,f.created_at desc;
$$;

create or replace function public.respond_constancce_friend(p_friendship_id bigint,p_accept boolean)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  if p_accept then
    update public.constancce_friendships set status='accepted',updated_at=now()
    where id=p_friendship_id and addressee_id=auth.uid() and status='pending';
  else
    delete from public.constancce_friendships where id=p_friendship_id and addressee_id=auth.uid() and status='pending';
  end if;
  if not found then raise exception 'friend request not found'; end if;
  return jsonb_build_object('ok',true);
end;
$$;

create or replace function public.remove_constancce_friend(p_friendship_id bigint)
returns jsonb language plpgsql security definer set search_path=public,auth as $$
begin
  if auth.uid() is null or not public.constancce_email_verified() then raise exception 'unauthorized'; end if;
  delete from public.constancce_friendships where id=p_friendship_id and (requester_id=auth.uid() or addressee_id=auth.uid());
  if not found then raise exception 'friendship not found'; end if;
  return jsonb_build_object('ok',true);
end;
$$;

revoke all on function public.add_constancce_friend(text) from public,anon;
revoke all on function public.get_constancce_friends() from public,anon;
revoke all on function public.respond_constancce_friend(bigint,boolean) from public,anon;
revoke all on function public.remove_constancce_friend(bigint) from public,anon;
grant execute on function public.add_constancce_friend(text) to authenticated;
grant execute on function public.get_constancce_friends() to authenticated;
grant execute on function public.respond_constancce_friend(bigint,boolean) to authenticated;
grant execute on function public.remove_constancce_friend(bigint) to authenticated;

create index if not exists constancce_profiles_email_lower_idx on public.constancce_profiles(lower(email));
create index if not exists constancce_friendships_requester_idx on public.constancce_friendships(requester_id);
create index if not exists constancce_friendships_addressee_idx on public.constancce_friendships(addressee_id);

-- --------------------------------------------------------------------------
-- 7. CHECKOUT / PAGAMENTOS
-- --------------------------------------------------------------------------
create table if not exists public.constancce_checkout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_code text not null,
  amount numeric(10,2) not null,
  currency text not null default 'BRL',
  preference_id text unique,
  status text not null default 'created',
  payment_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.constancce_payment_events (
  payment_id text primary key,
  checkout_session_id uuid references public.constancce_checkout_sessions(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  preference_id text,
  status text not null,
  amount numeric(10,2),
  currency text,
  payload jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.constancce_checkout_sessions enable row level security;
alter table public.constancce_payment_events enable row level security;
revoke all on table public.constancce_checkout_sessions from anon,authenticated;
revoke all on table public.constancce_payment_events from anon,authenticated;
create index if not exists constancce_checkout_sessions_user_idx on public.constancce_checkout_sessions(user_id,created_at desc);
create index if not exists constancce_payment_events_user_idx on public.constancce_payment_events(user_id,updated_at desc);

-- --------------------------------------------------------------------------
-- 8. MENOR PRIVILÉGIO PARA OBJETOS FUTUROS CRIADOS PELO OWNER
-- --------------------------------------------------------------------------
alter default privileges in schema public revoke all on tables from anon,authenticated;
alter default privileges in schema public revoke execute on functions from public,anon,authenticated;

commit;

-- Verificações opcionais após o RUN:
-- select grantee,table_name,privilege_type from information_schema.role_table_grants
-- where table_schema='public' and grantee in ('anon','authenticated') order by table_name,grantee,privilege_type;
-- select public.grant_constancce_pro('email-confirmado@exemplo.com',30);
